## Numpy

In [ ]:
import numpy as np

## create a array
## 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)

## 2D Array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 column



[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [6]:
np.arange(0,10,2)
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,5))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Numpy vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition", arr1+arr2)

print('Subtraction', arr1-arr2)

print('Multiplication', arr1 * arr2)

Addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]


In [12]:
## Universal Function

arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## Array slicing and indexing

arr= np.array([[1,3,4,5,6],[3,5,3,5,6],[6,7,8,9,4]])
print('Array: \n',arr)


Array: 
 [[1 3 4 5 6]
 [3 5 3 5 6]
 [6 7 8 9 4]]


In [15]:
arr[0][0]

print(arr[1:,2:])

print(arr[0:2,1:3])

[[3 5 6]
 [8 9 4]]
[[3 4]
 [5 3]]


In [17]:
## Modify array element

arr[0,0]=100
print(arr)

[[100   3   4   5   6]
 [  3   5   3   5   6]
 [  6   7   8   9   4]]


In [ ]:
## Statistical concept -Normalization

